"""add_proxy_port_to_profiles

Revision ID: b9d1eea63dd0
Revises: 003
Create Date: 2026-03-20 22:09:43.973684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d1eea63dd0'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_cookies_profile_id', table_name='profile_cookies')
    op.add_column('profiles', sa.Column('proxy_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'proxy_port')
    op.create_index('ix_profile_cookies_profile_id', 'profile_cookies', ['profile_id'], unique=False)
    # ### end Alembic commands ###
